version: 2
updates:
  # Updates for Github Actions used in the repo
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain dependencies for mobile module
  - package-ecosystem: "gradle"
    directory: "/mobile"
    schedule:
      interval: "daily"
    labels:
      - "mobile"
      - "dependencies"

  # Maintain dependencies for wear module
  - package-ecosystem: "gradle"
    directory: "/wear"
    schedule:
      interval: "daily"
    labels:
      - "wearos"
      - "dependencies"

  # Maintain dependencies for common module
  - package-ecosystem: "gradle"
    directory: "/common"
    schedule:
      interval: "daily"
    labels:
      - "common"
      - "dependencies"
