@file:Suppress("MagicNumber")
package com.boswelja.smartwatchextensions.core.ui.theme

import androidx.compose.ui.graphics.Color

/**
 * The alpha used for disabled components. Text, buttons etc.
 */
const val DisabledAlpha = 0.38f

internal val md_theme_light_primary = Color(0xFF9a25ae)
internal val md_theme_light_onPrimary = Color(0xFFffffff)
internal val md_theme_light_primaryContainer = Color(0xFFffd5ff)
internal val md_theme_light_onPrimaryContainer = Color(0xFF350040)
internal val md_theme_light_secondary = Color(0xFF6b586b)
internal val md_theme_light_onSecondary = Color(0xFFffffff)
internal val md_theme_light_secondaryContainer = Color(0xFFf5dbf2)
internal val md_theme_light_onSecondaryContainer = Color(0xFF251626)
internal val md_theme_light_tertiary = Color(0xFF82524a)
internal val md_theme_light_onTertiary = Color(0xFFffffff)
internal val md_theme_light_tertiaryContainer = Color(0xFFffdad2)
internal val md_theme_light_onTertiaryContainer = Color(0xFF32110c)
internal val md_theme_light_error = Color(0xFFba1b1b)
internal val md_theme_light_errorContainer = Color(0xFFffdad4)
internal val md_theme_light_onError = Color(0xFFffffff)
internal val md_theme_light_onErrorContainer = Color(0xFF410001)
internal val md_theme_light_background = Color(0xFFfcfcfc)
internal val md_theme_light_onBackground = Color(0xFF1e1a1d)
internal val md_theme_light_surface = Color(0xFFfcfcfc)
internal val md_theme_light_onSurface = Color(0xFF1e1a1d)
internal val md_theme_light_surfaceVariant = Color(0xFFecdee8)
internal val md_theme_light_onSurfaceVariant = Color(0xFF4d444c)
internal val md_theme_light_outline = Color(0xFF7e747c)
internal val md_theme_light_inverseOnSurface = Color(0xFFf7eef3)
internal val md_theme_light_inverseSurface = Color(0xFF332f32)
internal val md_theme_light_inversePrimary = Color(0xFFfbaaff)

internal val md_theme_dark_primary = Color(0xFFfbaaff)
internal val md_theme_dark_onPrimary = Color(0xFF570068)
internal val md_theme_dark_primaryContainer = Color(0xFF7b0091)
internal val md_theme_dark_onPrimaryContainer = Color(0xFFffd5ff)
internal val md_theme_dark_secondary = Color(0xFFd7bfd5)
internal val md_theme_dark_onSecondary = Color(0xFF3b2b3b)
internal val md_theme_dark_secondaryContainer = Color(0xFF534153)
internal val md_theme_dark_onSecondaryContainer = Color(0xFFf5dbf2)
internal val md_theme_dark_tertiary = Color(0xFFf6b8ae)
internal val md_theme_dark_onTertiary = Color(0xFF4c251f)
internal val md_theme_dark_tertiaryContainer = Color(0xFF663b34)
internal val md_theme_dark_onTertiaryContainer = Color(0xFFffdad2)
internal val md_theme_dark_error = Color(0xFFffb4a9)
internal val md_theme_dark_errorContainer = Color(0xFF930006)
internal val md_theme_dark_onError = Color(0xFF680003)
internal val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
internal val md_theme_dark_background = Color(0xFF1e1a1d)
internal val md_theme_dark_onBackground = Color(0xFFe9e0e5)
internal val md_theme_dark_surface = Color(0xFF1e1a1d)
internal val md_theme_dark_onSurface = Color(0xFFe9e0e5)
internal val md_theme_dark_surfaceVariant = Color(0xFF4d444c)
internal val md_theme_dark_onSurfaceVariant = Color(0xFFd0c3cc)
internal val md_theme_dark_outline = Color(0xFF998e96)
internal val md_theme_dark_inverseOnSurface = Color(0xFF1e1a1d)
internal val md_theme_dark_inverseSurface = Color(0xFFe9e0e5)
internal val md_theme_dark_inversePrimary = Color(0xFF9a25ae)
