name: Tag & Publish Beta

on:
  workflow_dispatch

jobs:
  sign:
    name: Sign and Save Bundles
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: 11
      - name: Cache Gradle Packages
        uses: actions/cache@v2.1.4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-cache-${{ hashFiles('**/*.gradle.kts') }}
      - name: Cache Gradle Wrapper
        uses: actions/cache@v2.1.4
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
      - name: Cache Build
        uses: actions/cache@v2.1.4
        with:
          path: ./**/build/
          key: ${{ runner.os }}-build-${{ github.sha }}
      - name: Build Mobile Release Artifacts
        run: ./gradlew :mobile:bundleRelease
      - name: Sign Mobile Release
        id: sign-mobile-release
        uses: r0adkll/sign-android-release@v1.0.4
        with:
          releaseDirectory: mobile/build/outputs/bundle/release/
          signingKeyBase64: ${{ secrets.KEYSTORE_FILE }}
          alias: ${{ secrets.KEYSTORE_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASS }}
          keyPassword: ${{ secrets.KEYSTORE_ALIAS_PASS }}
      - name: Save Signed Mobile Bundle
        uses: actions/upload-artifact@v2.2.3
        with:
          name: mobile-release.aab
          path: ${{ steps.sign-mobile-release.outputs.signedReleaseFile }}
      - name: Build Wear OS Release Artifacts
        run: ./gradlew :wearos:bundleRelease
      - name: Sign Wear OS Release
        id: sign-wearos-release
        uses: r0adkll/sign-android-release@v1.0.4
        with:
          releaseDirectory: wearos/build/outputs/bundle/release/
          signingKeyBase64: ${{ secrets.KEYSTORE_FILE }}
          alias: ${{ secrets.KEYSTORE_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASS }}
          keyPassword: ${{ secrets.KEYSTORE_ALIAS_PASS }}
      - name: Save Signed Wear OS Bundle
        uses: actions/upload-artifact@v2.2.3
        with:
          name: wearos-release.aab
          path: ${{ steps.sign-wearos-release.outputs.signedReleaseFile }}

  upload:
    name: Upload to Google Play & Create Release
    runs-on: ubuntu-latest
    needs: sign
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: 11
      - name: Download mobile-release.aab
        uses: actions/download-artifact@v2.0.9
        with:
          name: mobile-release.aab
          path: release/
      - name: Download wearos-release.aab
        uses: actions/download-artifact@v2.0.9
        with:
          name: wearos-release.aab
          path: release/
      - name: Get last release name
        uses: pozetroninc/github-action-get-latest-release@v0.5.0
        id: old_release
        with:
          repository: "boswelja/WearableExtensions"
          excludes: 'draft'
      - name: Get new release name
        uses: boswelja/aab-info-action@v1.0.10
        id: new_release
        with:
          aabPath: release/mobile-release.aab
      - name: Create Release Tag
        uses: actions/create-release@v1.1.4
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.new_release.outputs.versionName }}
          release_name: ${{ steps.new_release.outputs.versionName }}
          body_path: changelogs/whatsnew-en-GB
          draft: false
          prerelease: true
      - name: Upload Mobile Release Asset
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release/mobile-release.aab
          asset_name: mobile-release.aab
          asset_content_type: application/zip
      - name: Upload Wear OS Release Asset
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release/wearos-release.aab
          asset_name: wearos-release.aab
          asset_content_type: application/zip
      - name: Calculate update priority
        uses: boswelja/update-priority-action@main
        id: update_priority
        with:
          old-version: ${{ steps.old_release.outputs.release }}
          new-version: ${{steps.new_release.outputs.versionName }}
      - name: Upload to Google Play
        uses: r0adkll/upload-google-play@v1.0.15
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: "com.boswelja.devicemanager"
          releaseFiles: "release/mobile-release.aab,release/wearos-release.aab"
          whatsNewDirectory: changelogs/
          inAppUpdatePriority: ${{ steps.update_priority.outputs.update-priority }}
          track: beta
