name: Tag & Publish Beta

on:
  workflow_dispatch

jobs:
  build-sign:
    name: Build, Sign and Save Bundles
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0                # fetch the whole repo history

      - uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 17
          cache: 'gradle'

      - name: Git Version
        uses: codacy/git-version@2.8.0
        id: version
        with:
          release-branch: main

      - name: Build Mobile Release Artifacts
        run: ./gradlew :mobile:bundleRelease
        env:
          VERSION_NAME: ${{ steps.version.outputs.version }}

      - name: Sign Mobile Release
        id: sign-mobile-release
        uses: r0adkll/sign-android-release@v1.0.4
        with:
          releaseDirectory: mobile/build/outputs/bundle/release/
          signingKeyBase64: ${{ secrets.KEYSTORE_FILE }}
          alias: ${{ secrets.KEYSTORE_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASS }}
          keyPassword: ${{ secrets.KEYSTORE_ALIAS_PASS }}

      - name: Save Signed Mobile Bundle
        uses: actions/upload-artifact@v4
        with:
          name: mobile-release.aab
          path: ${{ steps.sign-mobile-release.outputs.signedReleaseFile }}

      - name: Build Wear OS Release Artifacts
        run: ./gradlew :wearos:bundleRelease
        env:
          VERSION_NAME: ${{ steps.version.outputs.version }}

      - name: Sign Wear OS Release
        id: sign-wearos-release
        uses: r0adkll/sign-android-release@v1.0.4
        with:
          releaseDirectory: wearos/build/outputs/bundle/release/
          signingKeyBase64: ${{ secrets.KEYSTORE_FILE }}
          alias: ${{ secrets.KEYSTORE_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASS }}
          keyPassword: ${{ secrets.KEYSTORE_ALIAS_PASS }}

      - name: Save Signed Wear OS Bundle
        uses: actions/upload-artifact@v4
        with:
          name: wearos-release.aab
          path: ${{ steps.sign-wearos-release.outputs.signedReleaseFile }}

  upload:
    name: Upload to Google Play & Create Release
    runs-on: ubuntu-latest
    needs: build-sign
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0                # fetch the whole repo history

      - name: Git Version
        uses: codacy/git-version@2.8.0
        id: version
        with:
          release-branch: main

      - name: Generate Changelog
        id: changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          stripHeaders: true
          releaseBranch: "main"
          pullRequests: true
          prWoLabels: true
          author: true
          compareLink: true
          onlyLastTag: true

      - name: Download mobile-release.aab
        uses: actions/download-artifact@v4
        with:
          name: mobile-release.aab
          path: release/

      - name: Download wearos-release.aab
        uses: actions/download-artifact@v4
        with:
          name: wearos-release.aab
          path: release/

      - name: Create Release Tag
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.version.outputs.version }}
          body: ${{ steps.changelog.outputs.changelog }}
          prerelease: true
          artifacts: "release/mobile-release.aab,release/wearos-release.aab"

      - name: Upload to Google Play
        uses: r0adkll/upload-google-play@v1.1.3
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: "com.boswelja.smartwatchextensions"
          releaseFiles: "release/mobile-release.aab,release/wearos-release.aab"
          whatsNewDirectory: config/whatsnew/
          track: beta
          status: completed
