name: Compile CI

on:
  push:
    paths-ignore:
      - '*.md'
    branches:
      - '*'
  pull_request:
    paths-ignore:
      - '*.md'
    branches:
      - 'main'

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: 11
      - name: Cache Gradle Packages
        uses: actions/cache@v2.1.2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-cache-${{ hashFiles('**/*.gradle.kts') }}
      - name: Cache Gradle Wrapper
        uses: actions/cache@v2.1.2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
      - name: Build
        run: bash ./gradlew assemble --stacktrace
