name: Main Quality Checks

on:
  push:
    branches:
      - 'main'

jobs:
  assemble:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: 11
      - name: Cache Gradle packages
        uses: actions/cache@v2.1.3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-cache-${{ hashFiles('**/*.gradle.kts') }}
      - name: Cache Gradle Wrapper
        uses: actions/cache@v2.1.3
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
      - name: Cache Build
        uses: actions/cache@v2.1.3
        with:
          path: ./**/build/
          key: ${{ runner.os }}-build-${{ github.sha }}
      - name: Build
        run: bash ./gradlew assemble --stacktrace

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: assemble
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: 11
      - name: Cache Gradle packages
        uses: actions/cache@v2.1.3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-cache-${{ hashFiles('**/*.gradle.kts') }}
      - name: Cache Gradle Wrapper
        uses: actions/cache@v2.1.3
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
      - name: Cache Build
        uses: actions/cache@v2.1.3
        with:
          path: ./**/build/
          key: ${{ runner.os }}-build-${{ github.sha }}
      - name: Unit tests
        run: bash ./gradlew test --stacktrace
      - uses: actions/upload-artifact@v2.2.2
        if: failure()
        with:
          name: Unit test results
          path: ./**/build/reports/tests/
          if-no-files-found: ignore

  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest
    needs: assemble
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: 11
      - name: Download Ktlint
        run: curl -o ktlint -L https://github.com/pinterest/ktlint/releases/download/0.40.0/ktlint && chmod +x ktlint
      - name: Run ktlint
        run: ./ktlint --android --reporter=checkstyle,output=ktlint_result.xml
      - uses: yutailang0119/action-ktlint@v1.0.0
        if: failure()
        with:
          xml_path: ktlint_result.xml
      - name: Cache Gradle Packages
        uses: actions/cache@v2.1.3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-cache-${{ hashFiles('**/*.gradle.kts') }}
      - name: Cache Gradle Wrapper
        uses: actions/cache@v2.1.3
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
      - name: Cache Build
        uses: actions/cache@v2.1.3
        with:
          path: ./**/build/
          key: ${{ runner.os }}-build-${{ github.sha }}
      - run: bash ./gradlew lint
      - uses: yutailang0119/action-android-lint@v1.0.2
        with:
          xml_path: mobile/build/reports/lint-results-debug.xml
      - uses: yutailang0119/action-android-lint@v1.0.2
        with:
          xml_path: wear/build/reports/lint-results-debug.xml
