name: Production Publish CI

on:
  push:
    paths-ignore:
      - '*.md'
    branches:
      - 'production'

jobs:
  sign:
    name: Sign and Save Bundles
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: 11
      - name: Cache Gradle Packages
        uses: actions/cache@v2.1.2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-cache-${{ hashFiles('**/*.gradle.kts') }}
      - name: Cache Gradle Wrapper
        uses: actions/cache@v2.1.2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
      - name: Build Mobile Release Artifacts
        run: ./gradlew :mobile:bundleRelease
      - name: Sign Mobile Release
        id: sign-mobile-release
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: mobile/build/outputs/bundle/release/
          signingKeyBase64: ${{ secrets.KEYSTORE_FILE }}
          alias: ${{ secrets.KEYSTORE_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASS }}
          keyPassword: ${{ secrets.KEYSTORE_ALIAS_PASS }}
      - name: Save Signed Mobile Bundle
        uses: actions/upload-artifact@v2.2.0
        with:
          name: mobile-release.aab
          path: ${{ steps.sign-mobile-release.outputs.signedReleaseFile }}
      - name: Build Wear Release Artifacts
        run: ./gradlew :wear:bundleRelease
      - name: Sign Wear Release
        id: sign-wear-release
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: wear/build/outputs/bundle/release/
          signingKeyBase64: ${{ secrets.KEYSTORE_FILE }}
          alias: ${{ secrets.KEYSTORE_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASS }}
          keyPassword: ${{ secrets.KEYSTORE_ALIAS_PASS }}
      - name: Save Signed Wear Bundle
        uses: actions/upload-artifact@v2.2.0
        with:
          name: wear-release.aab
          path: ${{ steps.sign-wear-release.outputs.signedReleaseFile }}

  upload:
    name: Upload to Google Play
    runs-on: ubuntu-latest
    needs: sign
    steps:
      - name: Download mobile-release.aab
        uses: actions/download-artifact@v2.0.5
        with:
          name: mobile-release.aab
          path: release/
      - name: Download wear-release.aab
        uses: actions/download-artifact@v2.0.5
        with:
          name: wear-release.aab
          path: release/
      - name: Upload to Google Play
        uses: boswelja/upload-google-play@master
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: "com.boswelja.devicemanager"
          releaseFiles: "release/mobile-release.aab,release/wear-release.aab"
          track: production
