name: Quality Checks

on:
  pull_request:
    branches:
      - 'main'
    paths-ignore:
      - 'changelogs/**'
      - '**.md'
      - '.github/*.yml'

jobs:
  assemble:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.5
      - uses: actions/setup-java@v2.3.1
        with:
          distribution: 'adopt'
          java-version: 11
          cache: 'gradle'
      - name: Build
        run: bash ./gradlew assemble --stacktrace

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: assemble
    steps:
      - uses: actions/checkout@v2.3.5
      - uses: actions/setup-java@v2.3.1
        with:
          distribution: 'adopt'
          java-version: 11
          cache: 'gradle'
      - name: Unit tests
        run: bash ./gradlew test --stacktrace
      - uses: actions/upload-artifact@v2.2.4
        if: failure()
        with:
          name: Unit test results
          path: ./**/build/reports/tests/
          if-no-files-found: ignore

  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest
    needs: assemble
    steps:
      - uses: actions/checkout@v2.3.5
      - uses: actions/setup-java@v2.3.1
        with:
          distribution: 'adopt'
          java-version: 11
          cache: 'gradle'
      - name: Run ktlint
        uses: musichin/ktlint-check@v1
        with:
          version: '0.42.1'
          annotate: true
          relative: true
      - run: bash ./gradlew lint
      - uses: yutailang0119/action-android-lint@v1.1.1
        if: ${{ always() }}
        continue-on-error: true
        with:
          xml_path: mobile/build/reports/lint-results-debug.xml
      - uses: yutailang0119/action-android-lint@v1.1.1
        if: ${{ always() }}
        continue-on-error: true
        with:
          xml_path: wearos/build/reports/lint-results-debug.xml
