name: Quality Checks

on:
  pull_request:
    branches:
      - 'main'
    paths-ignore:
      - 'changelogs/**'
      - '**.md'
      - '.github/*.yml'

jobs:
  assemble:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Cache Gradle packages
        uses: actions/cache@v2.1.6
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-cache-${{ hashFiles('gradle/libs.versions.toml') }}
      - name: Cache Gradle Wrapper
        uses: actions/cache@v2.1.6
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
      - name: Cache Build
        uses: actions/cache@v2.1.6
        with:
          path: ./**/build/
          key: ${{ runner.os }}-build-${{ github.sha }}
      - name: Build
        run: bash ./gradlew assemble --stacktrace

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: assemble
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Cache Gradle packages
        uses: actions/cache@v2.1.6
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-cache-${{ hashFiles('gradle/libs.versions.toml') }}
      - name: Cache Gradle Wrapper
        uses: actions/cache@v2.1.6
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
      - name: Cache Build
        uses: actions/cache@v2.1.6
        with:
          path: ./**/build/
          key: ${{ runner.os }}-build-${{ github.sha }}
      - name: Unit tests
        run: bash ./gradlew test --stacktrace
      - uses: actions/upload-artifact@v2.2.3
        if: failure()
        with:
          name: Unit test results
          path: ./**/build/reports/tests/
          if-no-files-found: ignore

  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest
    needs: assemble
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Run ktlint
        uses: le0nidas/ktlint-pr-comments@main
        with:
          repotoken: ${{ secrets.GITHUB_TOKEN }}
          arguments: "--android"
      - name: Cache Gradle Packages
        uses: actions/cache@v2.1.6
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-cache-${{ hashFiles('gradle/libs.versions.toml') }}
      - name: Cache Gradle Wrapper
        uses: actions/cache@v2.1.6
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
      - name: Cache Build
        uses: actions/cache@v2.1.6
        with:
          path: ./**/build/
          key: ${{ runner.os }}-build-${{ github.sha }}
      - run: bash ./gradlew lint
      - uses: yutailang0119/action-android-lint@v1.1.0
        if: ${{ always() }}
        continue-on-error: true
        with:
          xml_path: mobile/build/reports/lint-results-debug.xml
      - uses: yutailang0119/action-android-lint@v1.1.0
        if: ${{ always() }}
        continue-on-error: true
        with:
          xml_path: wearos/build/reports/lint-results-debug.xml
