name: Quality Checks

on:
  pull_request:
    branches:
      - 'main'
    paths-ignore:
      - '**.md'
      - '.github/*.yml'

jobs:
  assemble:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 17
          cache: 'gradle'

      - name: Build
        run: bash ./gradlew assembleDebug

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: assemble
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 17
          cache: 'gradle'

      - name: Unit tests
        run: bash ./gradlew testDebugUnitTest

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: Unit test results
          path: ./**/build/reports/tests/
          if-no-files-found: ignore

  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest
    needs: assemble
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 17
          cache: 'gradle'

      - run: bash ./gradlew detekt
